-- ═══════════════════════════════════════════════════════════════════════════
--  WhatToDo Jan Juc — database schema
--  Source of truth for the site. The spreadsheet becomes an export, not the
--  master copy. scripts/sync.py moves rows in both directions.
-- ═══════════════════════════════════════════════════════════════════════════

-- ── canonical vocabularies (from DATABASE_SCHEMA.md) ──────────────────────
create table if not exists types (
  name  text primary key,
  band  text not null check (band in ('place','community','event'))
);
insert into types (name, band) values
  ('beach','place'),('walk','place'),('surf','place'),('water','place'),
  ('bike track','place'),('skatepark','place'),('sport','place'),('park','place'),
  ('playground','place'),('nature','place'),('museum','place'),('cafe','place'),
  ('cinema','place'),('camping','place'),('at-home','place'),('night','place'),
  ('shop','place'),
  ('volunteering','community'),('nursery','community'),('cultural','community'),
  ('gig','event'),('festival','event'),('market','event'),('workshop','event'),
  ('community','event'),('sport-event','event')
on conflict (name) do nothing;

create table if not exists conditions (
  name text primary key,
  kind text not null check (kind in ('gate','boost'))
);
insert into conditions (name, kind) values
  ('any-weather','gate'),('low-tide','gate'),('high-tide','gate'),('new-moon','gate'),
  ('full-moon','gate'),('clear-sky','gate'),('calm-sea','gate'),('warm','gate'),
  ('low-wind','gate'),('dry-trails','gate'),('dry-ground','gate'),('no-fire-ban','gate'),
  ('geomagnetic-storm','gate'),('good-in-rain','boost')
on conflict (name) do nothing;

-- ── activities: evergreen places and things ───────────────────────────────
create table if not exists activities (
  id            bigint generated by default as identity primary key,
  name          text not null,
  type          text not null references types(name),
  tags          text[] default '{}',
  ages          text[] default '{}',
  cost          text check (cost in ('Free','Cheap','Moderate','Splurge')),
  location      text,
  km            numeric(5,1),
  season        text[] default '{}',
  duration      text,
  description   text,
  url           text,
  rating        smallint check (rating between 1 and 5),
  notes         text,
  conditions    text[] default '{any-weather}',
  lat           numeric(9,6),
  lng           numeric(9,6),
  daypart       text not null default 'day' check (daypart in ('day','night','both')),
  -- provenance
  added_by      text default 'Research',
  verified      boolean not null default false,
  source_note   text,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- ── events: time-bound things ─────────────────────────────────────────────
create table if not exists events (
  id             bigint generated by default as identity primary key,
  name           text not null,
  type           text not null references types(name),
  starts_on      date,
  ends_on        date,
  time_text      text,
  recurrence     text check (recurrence in ('none','weekly','fortnightly','monthly','annual')),
  venue          text,
  location       text,
  km             numeric(5,1),
  cost           text,
  ages           text[] default '{}',
  artist         text,
  genre          text,
  description    text,
  ticket_url     text,
  info_url       text,
  conditions     text[] default '{any-weather}',
  date_confidence text not null default 'low' check (date_confidence in ('high','medium','low')),
  added_by       text default 'Research',
  verified       boolean not null default false,
  source_note    text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

create index if not exists activities_type_idx  on activities(type);
create index if not exists activities_km_idx    on activities(km);
create index if not exists events_starts_idx    on events(starts_on);
create index if not exists events_type_idx      on events(type);

-- every condition tag must be in the vocabulary
create or replace function conditions_valid(tags text[]) returns boolean
language sql immutable as $$
  select coalesce(bool_and(t in (select name from conditions)), true) from unnest(tags) t
$$;
alter table activities drop constraint if exists activities_conditions_valid;
alter table activities add  constraint activities_conditions_valid check (conditions_valid(conditions));
alter table events     drop constraint if exists events_conditions_valid;
alter table events     add  constraint events_conditions_valid check (conditions_valid(conditions));

-- keep updated_at honest
create or replace function touch_updated_at() returns trigger
language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
drop trigger if exists activities_touch on activities;
create trigger activities_touch before update on activities
  for each row execute function touch_updated_at();
drop trigger if exists events_touch on events;
create trigger events_touch before update on events
  for each row execute function touch_updated_at();

-- ── row level security ────────────────────────────────────────────────────
-- Anyone may READ. Anyone may ADD, but never as verified and never as
-- "Research" — a community submission cannot dress itself up as researched
-- data. Only the service key (you, or scripts/sync.py) can edit or delete.
alter table activities enable row level security;
alter table events     enable row level security;
alter table types      enable row level security;
alter table conditions enable row level security;

drop policy if exists "read types"       on types;
drop policy if exists "read conditions"  on conditions;
create policy "read types"      on types      for select to anon, authenticated using (true);
create policy "read conditions" on conditions for select to anon, authenticated using (true);

drop policy if exists "public read"   on activities;
drop policy if exists "public add"    on activities;
create policy "public read" on activities for select to anon, authenticated using (true);
create policy "public add"  on activities for insert to anon, authenticated
  with check (verified = false and added_by is distinct from 'Research');

drop policy if exists "public read"   on events;
drop policy if exists "public add"    on events;
create policy "public read" on events for select to anon, authenticated using (true);
create policy "public add"  on events for insert to anon, authenticated
  with check (verified = false and added_by is distinct from 'Research');

-- ── what the site reads ───────────────────────────────────────────────────
-- One shape for both tables so the page has a single list to render.
create or replace view listings as
  select 'a'||id as key, id, false as is_event, name, type, location, km, cost, ages,
         description, coalesce(url, null) as url, null::text as info_url, null::text as ticket_url,
         conditions, rating, notes, duration, season, daypart,
         null::date as starts_on, null::text as time_text, null::text as recurrence,
         null::text as date_confidence, lat, lng, verified, added_by, created_at
    from activities
  union all
  select 'e'||id, id, true, name, type, coalesce(location, venue), km, cost, ages,
         description, info_url, info_url, ticket_url,
         conditions, null::smallint, null::text, null::text, '{}'::text[], 'day',
         starts_on, time_text, recurrence, date_confidence, null, null, verified, added_by, created_at
    from events;
