-- ── venues ───────────────────────────────────────────────────────────────
-- Run this whole file in the Supabase SQL editor. Do NOT build it by hand in
-- the Table Editor; a hand-made table gets only id and created_at.
--
-- Why: `venue` on events was free text — 42 different strings across 44 events,
-- already drifting ("Lorne Foreshore" / "Lorne foreshore" / "Lorne Foreshore &
-- Erskine Falls"). A venue is a real place with one address, so it gets a row,
-- and events point at it. That is also what lets events appear on a map: an
-- event has no coordinates of its own, its venue does.
--
-- Seeded from the music venue spreadsheet (47 rows). Not seeded: 8 venues in
-- Warrnambool and Port Fairy, 250-290km away and well outside the project's
-- stated scope, and "The Door Gallery Cafe", which has no suburb or address.
-- Apollo Bay (~110km) IS seeded — over the nominal 100km, but it is the Great
-- Ocean Road, which the scope names explicitly.
--
-- lat/lng are left null on purpose. Coordinates must come from a real geocoder,
-- not from guesswork; that is a separate pass.

create table if not exists venues (
  id             bigint generated by default as identity primary key,
  name           text not null unique,
  suburb         text,
  address        text,
  kind           text,
  website        text,
  events_url     text,
  ticketing_url  text,
  facebook       text,
  instagram      text,
  lat            numeric(9,6),
  lng            numeric(9,6),
  source_note    text,
  created_at     timestamptz not null default now(),
  updated_at     timestamptz not null default now()
);

alter table events     add column if not exists venue_id bigint references venues(id);
alter table activities add column if not exists venue_id bigint references venues(id);

create index if not exists events_venue_idx     on events(venue_id);
create index if not exists activities_venue_idx on activities(venue_id);

-- Anyone may read venues; nobody may write them from the browser.
alter table venues enable row level security;
drop policy if exists venues_read on venues;
create policy venues_read on venues for select using (true);

insert into venues (name, suburb, address, kind, website, events_url, ticketing_url, facebook, instagram, source_note) values
  ('Aireys Pub', 'Aireys Inlet', '45 Great Ocean Road, Aireys Inlet VIC 3231', 'Pub', 'http://aireyspub.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Apollo Bay Hotel', 'Apollo Bay', '95 Great Ocean Road, Apollo Bay VIC 3233', 'Hotel', 'https://apollobayhotel.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Barwon Club Hotel', 'Geelong', '509 Moorabool St, Geelong VIC 3220', 'Hotel', 'https://barwonclub.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Barwon Heads Hotel', 'Barwon Heads', null, 'Hotel', 'https://barwonheadshotel.com.au/', 'https://barwonheadshotel.com.au/gigs/', 'barwonheadshotel.oztix.com.au', 'https://www.facebook.com/BarwonHeadsHotel/events', 'https://www.instagram.com/barwonheadshotel/', 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Bellarine Estate Winery', 'Bellarine', '2270 Portarlington Rd, Bellarine VIC 3223', 'Winery', 'http://www.bellarineestate.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Bellbrae Estate', 'Bellbrae', '520 Great Ocean Road, Bellbrae VIC 3228', 'Winery', 'https://www.bellbraeestate.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Bells Beach Brewing', 'Torquay', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Bird Rock', 'Jan Juc', '2 Princes Terrace, Jan Juc VIC 3228', 'Bar', 'https://birdrockjj.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026. Address corrected: the sheet said 77 Sunset Strip; birdrockjj.com.au gives 2 Princes Terrace (a Yelp listing gives a third address, 1 Stuart Ave).'),
  ('Bloom', 'Geelong', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Bomboras', 'Torquay', '37 The Esplanade, Torquay VIC 3228', 'Bar', 'https://www.bomboras.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Cuda Bar', 'Lorne', '82 Mountjoy Parade, Lorne VIC 3232', 'Bar', 'http://www.cudabar.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Elephant & Castle Hotel', 'Geelong', '158 McKillop St, Geelong VIC 3220', 'Hotel', 'https://elephantandcastle.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Eureka Hotel Geelong', 'Geelong', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Flying Brick Cider Co', 'Wallington', '1251-1269 Bellarine Hwy, Wallington VIC 3221', 'Cidery', 'http://www.flyingbrickciderco.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Gateway Hotel', 'Corio', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Geelong Showgrounds', 'Geelong', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Grand Hotel Portarlington', 'Portarlington', null, null, 'https://www.portarlingtongrandhotel.com.au/whats-on/', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Great Ocean Road Brewhouse', 'Apollo Bay', '29/35 Great Ocean Rd, Apollo Bay VIC 3233', 'Brewery', 'https://greatoceanroadbrewhouse.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Lambys Tavern', 'Geelong', 'Basement Level, 66 Brougham St, Geelong', 'Bar', 'https://www.lambys.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Last One Inn', 'Anglesea', '143 Great Ocean Road, Anglesea VIC 3230', 'Pub', 'https://www.lastoneinn.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026. Sheet listed it as ''Last One Inn (Anglesea)''; suburb moved into its own column.'),
  ('Little Creatures Brewery', 'South Geelong', '221 Swanston St, South Geelong', 'Brewery', 'https://www.littlecreatures.com.au/locations/geelong', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Lorne Hotel', 'Lorne', '176 Mountjoy Parade, Lorne VIC 3232', 'Hotel', 'https://lornehotel.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Mt Duneed Estate', 'Waurn Ponds', null, 'Winery', null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Oneday Estate', 'Curlewis', '2255 Portarlington Rd, Curlewis VIC 3222', 'Winery', 'https://onedayestate.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Piano Bar Geelong', 'Geelong', '90 Little Malop St, Geelong VIC 3220', 'Piano Bar', 'https://pianobar.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Princess Park Playground', 'Queenscliff', null, 'Showground', null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Provenance Wines', 'Fyansford', '100 Fyansford-Gheringhap Road, Fyansford', 'Winery', 'https://provenancewines.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Queenscliff Brewhouse', 'Queenscliff', '2 Gellibrand St, Queenscliff VIC 3225', 'Brewery', 'https://queenscliffbrewhouse.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Saints and Sailors', 'Portarlington', '70-74 Newcombe St, Portarlington VIC 3223', 'Bar', 'https://saintsandsailors.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('The 18th Amendment Bar', 'Geelong', '82A Little Malop St, Geelong VIC 3220', 'Bar', 'https://www.the18thamendmentbar.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('The Playhouse', 'Geelong', null, 'Performing Arts Centre', null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('The Sound Doctor', 'Anglesea', '1B McMillan St, Anglesea VIC 3230', 'Live Music Venue', 'http://thesounddoctor.info', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026. Sheet listed it as ''The Sound Doctor (Anglesea Memorial Hall)''; it is the Anglesea Memorial Hall.'),
  ('The Whiskery', 'Drysdale', '2-4 Campbell Ln, Drysdale VIC 3222', 'Distillery', 'https://www.thewhiskery.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('The Wool Exchange Entertainment Complex', 'Geelong', '44 Corio St, Geelong VIC 3206', 'Entertainment Venue', 'https://www.thewoolexchange.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Torquay Bowls Club', 'Torquay', null, null, 'https://www.torquaybowlsclub.com/', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Torquay Common', 'Torquay', null, null, null, null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Torquay Hotel', 'Torquay', '36 Bell St, Torquay VIC 3228', 'Hotel', 'https://torquayhotel.com.au', 'https://torquayhotel.com.au/gigs/', 'torquayhotel.oztix.com.au', 'https://www.facebook.com/TorquayHotel/events', 'https://www.instagram.com/torquayhotel/', 'Seeded from the music venue spreadsheet, 24 Aug 2026.'),
  ('Workers Club Geelong', 'Geelong', '90-92 Little Malop St, Geelong VIC 3220', 'Entertainment Venue', 'http://www.theworkersclub.com.au', null, null, null, null, 'Seeded from the music venue spreadsheet, 24 Aug 2026.')
on conflict (name) do nothing;

-- The site reads `listings`. Rebuild it so an event inherits its venue's
-- coordinates, and an activity can too. Everything else is unchanged.
create or replace view listings as
  select 'a'||a.id as key, a.id, false as is_event, a.name, a.type, a.location, a.km, a.cost, a.ages,
         a.description, a.url, null::text as info_url, null::text as ticket_url,
         a.conditions, a.rating, a.notes, a.duration, a.season, a.daypart,
         null::date as starts_on, null::text as time_text, null::text as recurrence,
         null::text as date_confidence,
         coalesce(a.lat, av.lat) as lat, coalesce(a.lng, av.lng) as lng,
         a.verified, a.added_by, a.created_at
    from activities a left join venues av on av.id = a.venue_id
  union all
  select 'e'||e.id, e.id, true, e.name, e.type, coalesce(e.location, e.venue), e.km, e.cost, e.ages,
         e.description, e.info_url, e.info_url, e.ticket_url,
         e.conditions, null::smallint, null::text, null::text, '{}'::text[], 'day',
         e.starts_on, e.time_text, e.recurrence, e.date_confidence,
         ev.lat, ev.lng,
         e.verified, e.added_by, e.created_at
    from events e left join venues ev on ev.id = e.venue_id;

select (select count(*) from venues) as venues_seeded;